export const SET_ACCESSIBILITY_SELECTOR = 'SET_ACCESSIBILITY_SELECTOR';
export const SET_ACTIVE_NAV_INDEX = 'SET_ACTIVE_NAV_INDEX';
export const SET_NAV_MARKER_COUNT = 'SET_NAV_MARKER_COUNT';
export const SET_ACTIVE_HOTSPOT_INDEX = 'SET_ACTIVE_HOTSPOT_INDEX';
export const SET_HOTSPOT_MARKER_COUNT = 'SET_HOTSPOT_MARKER_COUNT';
