export const SET_TOTAL_NAV_MARKER_INDEXES = 'SET_TOTAL_NAV_MARKER_INDEXES';
export const RESET_CURRENT_ACCESSIBILITY_NAV_IDX =
	'RESET_CURRENT_ACCESSIBILITY_NAV_IDX';
export const HANDLE_LEFT_ARROW_KEY_ACCESSIBILITY_NAV_IDX =
	'HANDLE_LEFT_ARROW_KEY_ACCESSIBILITY_NAV_IDX';
export const HANDLE_RIGHT_ARROW_KEY_ACCESSIBILITY_NAV_IDX =
	'HANDLE_RIGHT_ARROW_KEY_ACCESSIBILITY_NAV_IDX';
